version: '3.8'

services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis

  celery:
    build: ./project
    command: celery --app=core worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./project:/usr/src/app
    depends_on:
      - web
      - redis

  redis:
    image: redis:7-alpine

  dashboard:
    build: ./project
    command: celery flower -A core --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    depends_on:
      - web
      - redis
      - celery